import type { NextPage } from "next";
import Head from "next/head";

import { ContactSection } from "../components/sections/contact";
import { LandingSection } from "../components/sections/landing";
import { PortfolioSection } from "../components/sections/portfolio";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Huzaifah.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="Home">
        <div style={{ overflow: "auto", scrollSnapType: "y proximity" }}>
          <div className="todo">TODO: Update website content with latest work... it's old</div>
          <LandingSection />
          <PortfolioSection />
          <ContactSection />
        </div>

        <footer style={{ padding: "0.2rem" }}>
          <div style={{ display: "flex", gap: "0.5rem", fontWeight: "bold" }}>
            <a target="_blank" rel="noreferrer" href="https://Linkedin.com/in/huzaifah-asif">
              LinkedIn
            </a>
            |
            <a target="_blank" rel="noreferrer" href="https://github.com/huzaifah0x00">
              Github
            </a>
          </div>
        </footer>
      </main>

      <div style={{ display: "none", height: "100vh", placeItems: "center" }} className="not-responsive-message">
        <h1 style={{ textAlign: "center" }}>This website is not viewable on small screens.</h1>
      </div>
    </div>
  );
};

export default Home;
